name = "revastra-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "greatstack"
ADMIN_EMAIL = "admin@revastra.com"
ADMIN_PASSWORD = "admin@0027"
CLOUDINARY_NAME = "dx517wcn7"
CLOUDINARY_API_KEY = "812751128828484"
CLOUDINARY_SECRET_KEY = "QJM97ds3h4TpZortNdZeNxPyWaY"

[[d1_databases]]
binding = "DB"
database_name = "revastra-db"
database_id = "44f5c759-d008-49e5-b0df-346946133a12"
